# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  dockerwebapilearning:
    image: dockerwebapilearning
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000
