version: '3.4'

services:
  dockerlearningwebapiservice:
    build: .
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=Dilip
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Docker.WebAPI.Learning.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
